src/AppBundle/Entity/Module/PollModule.php
<?php

namespace AppBundle\Entity\Module;

use AppBundle\Entity\Event\Module;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;


/**
 * PollModule
 *
 * @ORM\Table(name="module_poll_module")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\Module\PollModuleRepository")
 */
class PollModule
{
    /** Active les timestamps automatiques pour la creation et la mise a jour */
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="voting_type", type="enum_pollmodule_votingtype")
     */
    private $votingType;

    /**
     * Contient le type de module, utile pour les module pré-défini qui ont des traitements spécifiques, null sinon
     *
     * @var string
     *
     * @ORM\Column(name="poll_module_type", type="enum_pollmodule_type", nullable=true)
     */
    private $type;

    /**
     * If "true" then guests can add poll proposal
     * @var boolean
     * @ORM\Column(name="guests_can_add_proposal", type="boolean")
     */
    private $guestsCanAddProposal = true;

    /***********************************************************************
     *                      Jointures
     ***********************************************************************/

    /**
     * @var Module
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Event\Module", inversedBy="pollModule")
     * @ORM\JoinColumn(name="module_id", referencedColumnName="id")
     */
    private $module;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Module\PollProposal", mappedBy="pollModule", cascade={"persist"})
     */
    private $pollProposals;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Module\PollElement", mappedBy="pollModule", cascade={"persist"})
     */
    private $pollElements;


    /***********************************************************************
     *                      Constructor
     ***********************************************************************/
    public function __construct()
    {
        $this->pollProposals = new ArrayCollection();
        $this->pollElements = new ArrayCollection();
    }


    /***********************************************************************
     *                      Getters and Setters
     ***********************************************************************/

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getVotingType()
    {
        return $this->votingType;
    }

    /**
     * @param string $votingType
     * @return PollModule
     */
    public function setVotingType($votingType)
    {
        $this->votingType = $votingType;
        return $this;
    }

    /**
     * @return bool
     */
    public function isGuestsCanAddProposal()
    {
        return $this->guestsCanAddProposal;
    }

    /**
     * @param bool $guestsCanAddProposal
     * @return PollModule
     */
    public function setGuestsCanAddProposal($guestsCanAddProposal)
    {
        $this->guestsCanAddProposal = $guestsCanAddProposal;
        return $this;
    }

    /**
     * @return Module
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     * @param Module $module
     * @return PollModule
     */
    public function setModule($module)
    {
        $this->module = $module;
        return $this;
    }

    /**
     * Get proposals
     *
     * @return ArrayCollection
     */
    public function getPollProposals()
    {
        return $this->pollProposals;
    }

    /**
     * Add proposal
     *
     * @param PollProposal $pollProposal
     *
     * @return PollModule
     */
    public function addPollProposal(PollProposal $pollProposal)
    {
        $this->pollProposals[] = $pollProposal;
        $pollProposal->setPollModule($this);

        return $this;
    }

    /**
     * TODO set Status
     * Remove proposal
     * @param PollProposal $pollProposal
     */
    public function removePollProposal(PollProposal $pollProposal)
    {
        $this->pollProposals->removeElement($pollProposal);
    }

    /**
     * @return ArrayCollection
     */
    public function getPollElements()
    {
        return $this->pollElements;
    }

    /**
     * @param PollElement $pollElement
     * @return PollModule
     */
    public function addPollElement(PollElement $pollElement)
    {
        $this->pollElements[] = $pollElement;
        $pollElement->setPollModule($this);

        return $this;
    }

    /**
     * @param ArrayCollection $pollElements
     * @return PollModule
     */
    public function addPollElements(ArrayCollection $pollElements)
    {
        foreach ($pollElements as $pollElement) {
            $this->addPollElement($pollElement);
        }
        return $this;
    }

    /**
     * @param PollElement $pollElement
     */
    public function removePollElement(PollElement $pollElement)
    {
        $this->pollElements->removeElement($pollElement);
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }


    /***********************************************************************
     *                      Helpers
     ***********************************************************************/

    /**
     * Get the proposal by its Id
     *
     * @param $pollProposalId
     * @return PollProposal|null
     */
    public function getPollProposalById($pollProposalId)
    {
        $criteria = Criteria::create()->where(
            Criteria::expr()->eq('id', $pollProposalId)
        );
        return $this->pollProposals->matching($criteria)->get(0);
    }

    public function getValidPollProposal()
    {
        //if not pollProposal.deleted and pollProposal.id is not null
        $criteria = Criteria::create()->where(
            Criteria::expr()->andX(
                Criteria::expr()->eq("deleted", false),
                Criteria::expr()->neq("id", null)
            )
        );
        return $this->pollProposals->matching($criteria);
    }

    /**
     * @return ArrayCollection
     */
    public function getOrderedPollElements()
    {
        $criteria = Criteria::create()
            ->orderBy(["orderIndex" => Criteria::ASC]);
        return $this->pollElements->matching($criteria);
    }

}

src/AppBundle/Form/Event/EventCoordinatesType.php
<?php
/**
 * Created by PhpStorm.
 * User: Flavien
 * Date: 15/06/2016
 * Time: 18:05
 */

namespace AppBundle\Form\Event;

use AppBundle\Entity\Event\EventCoordinates;
use AppBundle\Form\Type\UrlDomaineType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Url;

class EventCoordinatesType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("website", UrlType::class, array(
                'required' => false,
                'constraints' => new Url()
            ))
            ->add("email", EmailType::class, array(
                'required' => false,
                'constraints' => new Email()))
            ->add("phoneNumber", TextType::class, array(
                'required' => false,))
            ->add("mobileNumber", TextType::class, array(
                'required' => false,))
            ->add("facebookURL", UrlDomaineType::class, array(
                'required' => false,
                'url_domain' => 'https://www.facebook.com/',
                'constraints' => new Url()
            ))
            ->add("googlePlusURL", UrlDomaineType::class, array(
                'required' => false,
                'url_domain' => 'https://plus.google.com/+',
                'constraints' => new Url()
            ))
            ->add("twitterURL", UrlDomaineType::class, array(
                'required' => false,
                'url_domain' => 'https://twitter.com/',
                'constraints' => new Url()
            ))
            ->add("instagramURL", UrlDomaineType::class, array(
                'required' => false,
                'url_domain' => 'https://www.instagram.com/',
                'constraints' => new Url()
            ))
            ->add("youtubeURL", UrlDomaineType::class, array(
                'required' => false,
                'url_domain' => 'https://www.youtube.com/',
                'constraints' => new Url()
            ))
            ->add("tripAdvisorURL", UrlType::class, array(
                'required' => false,
                'constraints' => new Url()
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => EventCoordinates::class
        ));
    }
}

src/AppBundle/Form/Event/EventInvitationAnswerType.php
<?php
/**
 * Created by PhpStorm.
 * User: Flavien
 * Date: 03/11/2016
 * Time: 13:50
 */

namespace AppBundle\Form\Event;


use AppBundle\Entity\Event\EventInvitation;
use AppBundle\Utils\enum\EventInvitationAnswer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventInvitationAnswerType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $formEvent) {
                /** @var FormInterface $form */
                $form = $formEvent->getForm();
                /** @var EventInvitation $eventInvitation */
                $eventInvitation = $formEvent->getData();

                $event = $eventInvitation->getEvent();

                // Todo: décommenter
                // Désactivation temporaire pour simplification
                //if ($event->getStatus() == EventStatus::IN_CREATION || $event->getStatus() == EventStatus::IN_ORGANIZATION || $event->getStatus() == EventStatus::AWAITING_VALIDATION) {
                if (false) {
                    $form->add('answer', ChoiceType::class, array(
                        'required' => true,
                        'expanded' => true,
                        'multiple' => false,
                        'choices' => array(
                            EventInvitationAnswer::INTERESTED => EventInvitationAnswer::INTERESTED,
                            EventInvitationAnswer::NOT_INTERESTED => EventInvitationAnswer::NOT_INTERESTED
                        ),
                        'choice_attr' => function ($val, $key, $index) {
                            if ($val == EventInvitationAnswer::INTERESTED) {
                                $data_class = 'btn-answer-true zmdi zmdi-check';
                            } else {
                                $data_class = 'btn-answer-false zmdi zmdi-close';
                            }
                            return ['dataclass' => $data_class];
                        },
                        'choice_label' => false
                    ));
                    //} elseif ($event->getStatus() == EventStatus::VALIDATED) {
                } elseif (true) {
                    $form->add('answer', ChoiceType::class, array(
                        'required' => true,
                        'expanded' => true,
                        'multiple' => false,
                        'choices' => array(
                            EventInvitationAnswer::YES => EventInvitationAnswer::YES,
                            EventInvitationAnswer::DONT_KNOW => EventInvitationAnswer::DONT_KNOW,
                            EventInvitationAnswer::NO => EventInvitationAnswer::NO
                        ),
                        'choice_attr' => function ($val, $key, $index) {
                            if ($val == EventInvitationAnswer::YES) {
                                $data_class = 'btn-answer-true zmdi zmdi-check';
                            } elseif ($val == EventInvitationAnswer::NO) {
                                $data_class = 'btn-answer-false zmdi zmdi-close';
                            } else {
                                $data_class = 'btn-answer-maybe fa fa-question';
                            }
                            return ['dataclass' => $data_class];
                        },
                        'choice_label' => function ($val, $key, $index) {
                            if ($val == EventInvitationAnswer::YES) {
                                return false;
                            } elseif ($val == EventInvitationAnswer::NO) {
                                return false;
                            } else {
                                return false;
                            }
                        }
                    ));
                }
            });

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => EventInvitation::class
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return "event_invitation_anwser";
    }
}

src/AppBundle/Form/Event/EventInvitationType.php
<?php
/**
 * Created by PhpStorm.
 * User: Flavien
 * Date: 13/07/2016
 * Time: 16:31
 */

namespace AppBundle\Form\Event;


use AppBundle\Entity\Event\EventInvitation;
use AppBundle\Validator\Constraints\EmailNotBelongToAccountUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class EventInvitationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $formEvent) {
            /** @var Form $form */
            $form = $formEvent->getForm();
            /** @var EventInvitation $eventInvitation */
            $eventInvitation = $formEvent->getData();
            $displayableName = $eventInvitation->getDisplayableName(false);
            $form
                ->add('guestName', TextType::class, array(
                    'required' => true,
                    'data' => $displayableName,
                    'constraints' => new NotBlank()
                ));
            $email = $eventInvitation->getDisplayableEmail();
            $form->add('email', EmailType::class, array(
                'required' => false,
                'mapped' => false,
                'data' => $email,
                'disabled' => ($eventInvitation->getApplicationUser() != null),
                'constraints' => ($eventInvitation->getApplicationUser() == null ? new EmailNotBelongToAccountUser() : null)
            ));
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => EventInvitation::class
        ));
    }
}

src/AppBundle/Form/Event/EventOpeningHoursType.php
<?php
/**
 * Created by PhpStorm.
 * User: Flavien
 * Date: 09/02/2017
 * Time: 16:20
 */

namespace AppBundle\Form\Event;

use AppBundle\Entity\Event\EventOpeningHours;
use AppBundle\Form\Type\DayOfWeekType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;


class EventOpeningHoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dayOfWeek', DayOfWeekType::class, array(
                'required' => true,
                'constraints' => new NotBlank()
            ))
            ->add('timeOpen', TimeType::class, array(
                'required' => false,
                'widget' => 'single_text'
            ))
            ->add('timeClosed', TimeType::class, array(
                'required' => false,
                'widget' => 'single_text'
            ));
    }

    public function getBlockPrefix()
    {
        return 'event_openinghours';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => EventOpeningHours::class
        ));
    }
}

src/AppBundle/Resources/views/Event/module/displayAddModule_card.html.twig
{# Données d'entrée :
- event (Event) Evenement affiché
- wizard (boolean) Si true Alors dans le wizard
#}

<div class="row">
    <div class="col-xs-3 col-sm-2 col-sm-offset-1 text-center">
        <a class="add-pollmodule-link" href="{{ url('addEventModule', {'token': event.token,'type':constant('AppBundle\\Utils\\enum\\ModuleType::POLL_MODULE'),
            'subtype':constant('AppBundle\\Utils\\enum\\PollModuleType::ACTIVITY'),'wizard':wizard}) }}" id="addActivityPollModule"> <i class="waves-effect zmdi zmdi-ticket-star zmdi-hc-3x"></i>
            <p>{{ "pollmodule.add_link.activity"|trans }}</p></a>
    </div>
    <div class="col-xs-3 col-sm-2 text-center">
        <a class="add-pollmodule-link" href="{{ url('addEventModule', {'token': event.token,'type':constant('AppBundle\\Utils\\enum\\ModuleType::POLL_MODULE'),
            'subtype':constant('AppBundle\\Utils\\enum\\PollModuleType::WHEN'),'wizard':wizard}) }}" id="addWhenPollModule"> <i class="waves-effect zmdi zmdi-calendar zmdi-hc-3x"></i>
            <p>{{ "pollmodule.add_link.when"|trans }}</p></a>
    </div>
    <div class="col-xs-3 col-sm-2 text-center">
        <a class="add-pollmodule-link" href="{{ url('addEventModule', {'token': event.token,'type':constant('AppBundle\\Utils\\enum\\ModuleType::POLL_MODULE'),
            'subtype':constant('AppBundle\\Utils\\enum\\PollModuleType::WHERE'),'wizard':wizard}) }}" id="addWherePollModule"> <i class="waves-effect zmdi zmdi-pin zmdi-hc-3x"></i>
            <p>{{ "pollmodule.add_link.where"|trans }}</p></a>
    </div>
    <div class="col-xs-3 col-sm-2 text-center">
        <a class="add-pollmodule-link" href="{{ url('addEventModule', {'token': event.token,'type':constant('AppBundle\\Utils\\enum\\ModuleType::POLL_MODULE'),
            'subtype':constant('AppBundle\\Utils\\enum\\PollModuleType::WHO_BRINGS_WHAT'),'wizard':wizard}) }}" id="addWhoBringsWhatPollModule"> <i class="waves-effect zmdi zmdi-format-list-bulleted zmdi-hc-3x"></i>
            <p>{{ "pollmodule.add_link.whobringswhat"|trans }}</p></a>
    </div>
    <div class="col-xs-3 col-sm-2 text-center">
        <a class="add-pollmodule-link" href="{{ url('addEventModule', {'token': event.token, 'type':constant('AppBundle\\Utils\\enum\\ModuleType::POLL_MODULE'),
            'subtype':constant('AppBundle\\Utils\\enum\\PollModuleType::WHAT'),'wizard':wizard}) }}" id="addWhatPollModule"> <i class="waves-effect zmdi zmdi-pin-help zmdi-hc-3x"></i>
            <p>{{ "pollmodule.add_link.what"|trans }}</p></a>
    </div>


    <script>
        $(document).ready(function () {
            $('.add-pollmodule-link').on('click', function (e) {
                var target = $(this);
                e.preventDefault();
                if (!target.hasClass('disabled')) {
                    $('.add-pollmodule-link').addClass("disabled");
                    if (!eventInvitationValid && askGuestName !== undefined) {
                        askGuestName(e, addModuleAction, [target, e], function () {
                            $('.add-pollmodule-link').removeClass("disabled");
                        });
                    } else {
                        addModuleAction([target, e]);
                    }
                }
            });
        })
    </script>
</div>

src/AppBundle/Resources/views/Event/module/displayModule.html.twig
{# Données d'entrée :
- module (Module) Le module à afficher
- moduleForm (Form|null) Le formulaire d'édition du module
- userModuleInvitation (ModuleInvitation) L'invitation du module de l'utilisateur connecté
- thread (Thread) Le fil de discussion du module
- comments(Comment[]) Les commentaires appartenant au fil de discussion du module
#}


<div class="card z-depth-1 {% block moduleCardClass %}c-dark{% endblock %}" id="module-{{ module.token }}">
    <span class="anchor-offset" id="module-{{ module.token }}_anchor"></span>
    {{ include("@App/Event/module/displayModule_header.html.twig", {'module':module, 'moduleForm':moduleForm, 'userModuleInvitation':userModuleInvitation}) }}

    {{ include('@App/Event/module/displayModule_informations.html.twig', {'module':module, 'userModuleInvitation':userModuleInvitation}) }}

    {% block moduleBody %}{% endblock moduleBody %}

    <div class="{% block moduleFooterClass %}card-footer{% endblock moduleFooterClass %}">
        {% block moduleFooter %}{% endblock moduleFooter %}

        {% block moduleDiscussion %}
            {% if thread is defined and thread is not null %}
                <div id="module_{{ module.token }}_comment_thread" data-thread="{{ thread.id }}" class="commentable_thread wall-comment-list">
                    <span class="anchor-offset" id="module_{{ module.token }}_comment_thread_anchor"></span>
                    {% include 'FOSCommentBundle:Thread:comments.html.twig' with {'comments':comments, 'thread':thread, 'view':'flat', 'userEventInvitation':userModuleInvitation.eventInvitation} %}
                </div>
                <script>
                    $(document).ready(function () {
                        if (typeof window.fos !== 'undefined' && typeof window.fos.Comment !== "undefined") {
                            window.fos.Comment.thread_container = $('.commentable_thread ');
                            window.fos.Comment.initializeListeners();
                        }
                        /** Fonction pour eviter le double envoi de commentaire */
                        $('#module_{{ module.token }}_comment_thread')
                            .on('fos_comment_add_comment', function (event, commentHtml) {
                                $('#module_{{ module.token }}_comment_thread .fos_comment_submit > button[type=submit], #module_{{ module.token }}_comment_thread .fos_comment_submit > input[type=submit]').removeAttr("disabled");
                            })
                            .on('fos_comment_submitting_form', function () {
                                $('#module_{{ module.token }}_comment_thread .fos_comment_submit > button[type=submit], #module_{{ module.token }}_comment_thread .fos_comment_submit > input[type=submit]').attr("disabled", "disabled");
                            });
                    });
                </script>
            {% endif %}
        {% endblock moduleDiscussion %}
    </div>

    <div id="modal-container-block-{{ module.token }}">
        {% if is_granted(constant('AppBundle\\Security\\ModuleVoter::EDIT'), [module, userModuleInvitation]) %}
            {{ include('@App/Event/module/displayModule_edition_modal.html.twig', {'module':module, 'moduleForm':moduleForm} ) }}
        {% endif %}
        {% block module_modal_container %}{% endblock module_modal_container %}
    </div>

    {% block JSmodule %}{% endblock %}
</div>

src/AppBundle/Resources/views/Event/module/displayModule_edition_modal.html.twig
{# Modale d'edition du module :
Données d'entrée :
- module (Module) Le module à afficher
- moduleForm (Form) Le formulaire d'édition du module
#}

<div class="modal fade" id="moduleEdit_modal_{{ module.token }}" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="#mhms_title" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="zmdi zmdi-close"></i></span></button>
                <h3 id="mhms_title" class="modal-title">{{ "module.modal.settings.title"|trans }}</h3>
            </div>
            <div class="modal-body">
                {{ include('@App/Event/module/displayModule_form.html.twig', {'module':module, 'moduleForm':moduleForm}) }}
            </div>
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Event/module/displayPollModule.html.twig
{% extends "@App/Event/module/displayModule.html.twig" %}

{# Données d'entrée :
- module (Module) Le module à afficher
- moduleForm (Form|null) Le formulaire d'édition du module
- userModuleInvitation (ModuleInvitation) L'invitation du module de l'utilisateur connecté
- pollModuleOptions (Array), contains:
        - pollProposalAddForm (Form|null) Le formulaire d'ajout d'une proposition
        - pollProposalListAddForm (Form|null) Le formulaire d'ajout de plusieurs propositions
#}


{% set maxColModule = constant("AppBundle\\Manager\\ModuleInvitationManager::MAX_COLUMN_DISPLAYABLE") %}
{% set add_pp_form_modal_prefix = 'add_pp_fm_'~module.token %}

{% block moduleCardClass %}{{ parent() }}{% endblock moduleCardClass %}
{% block moduleHeaderClass %}{{ parent() }}{% endblock moduleHeaderClass %}
{% block moduleHeaderAttributs %}{{ parent() }}{% endblock moduleHeaderAttributs %}

{% block moduleBody %}
    {% if module.pollModule is not null %}
        <div class="card-body card-padding-xs">
            {% set proposalList = module.pollModule.validPollProposal %}
            <div class="w-100 poll-container">
                <table id="pollmodule-table-{{ module.token }}" class="table-striped w-100">
                    <tbody id="pp-row-group-{{ module.token }}">
                    {# Pour chaque proposition #}
                    {% for pollProposal in module.pollModule.pollProposals if not pollProposal.deleted and pollProposal.id is not null %}
                        {{ include('@App/Event/module/pollModulePartials/pollProposalGuestResponseRowDisplay.html.twig', {
                            "pollProposal":pollProposal,
                            "userModuleInvitation":userModuleInvitation,
                            "moduleInvitations":module.filteredModuleInvitations
                        }) }}
                    {% endfor %}
                    <tr class="tr-no-proposal">
                        <td colspan="3">{{ "pollmodule.display.no_proposal"|trans }}</td>
                    </tr>
                    </tbody>
                    {% if pollModuleOptions.pollProposalAddForm is defined and pollModuleOptions.pollProposalAddForm is not null %}
                        <tfoot>
                        <tr>
                            <td colspan="3">
                                <a id="{{ add_pp_form_modal_prefix }}_modal_open_link" class="btn btn-link btn-icon-text c-blue p-l-0" href="#{{ add_pp_form_modal_prefix }}_modal_id"> <i
                                            class="zmdi zmdi-plus-square"></i>{{ "pollmodule.modal.addPollProposal.title"|trans }}</a>
                                <script>
                                    $('#{{ add_pp_form_modal_prefix }}_modal_open_link').on('click', function (e) {
                                        var modalId = $(this).attr('href');
                                        if (!eventInvitationValid && askGuestName !== undefined) {
                                            e.preventDefault();
                                            askGuestName(e, function () {
                                                $(modalId).modal('show');
                                            });
                                        } else {
                                            $(modalId).modal('show');
                                        }
                                    });
                                </script>
                                {{ include('@App/Event/module/pollModulePartials/pollProposal_form_modal.html.twig', {
                                    'userModuleInvitation' : userModuleInvitation,
                                    'pollModuleOptions' : pollModuleOptions,
                                    'pp_form_modal_prefix' : add_pp_form_modal_prefix,
                                    'edition' : false
                                }) }}
                            </td>
                        </tr>
                        </tfoot>
                    {% endif %}
                </table>
            </div>

            <div class="pollModuleDisplayAllResult text-center m-t-10 m-b-10">
                <a class="btn btn-link b-1 waves-effect" id="pollModuleDisplayAllResult_{{ module.token }}_button" href="{{ path('pollModuleDisplayResultTable', {"moduleToken": module.token }) }}"
                   role="button" {% if proposalList is empty %}style="display: none;"{% endif %}>{{ "pollmodule.display.result.allresult"|trans }}</a>
                <script>
                    $('#pollModuleDisplayAllResult_{{ module.token }}_button').on('click', function (e) {
                        ajaxRequest($(this), null, e, function (responseJSON, textStatus, jqXHR) {
                            LetterAvatar.transform();
                            closeModalOnReturn('#pollModuleDisplayAllResult_{{ module.token }}_modal');
                            $('#pollModuleDisplayAllResult_{{ module.token }}_modal').modal('show');
                        }, null, null);
                    });
                </script>
            </div>

            {# Conteneur pour la modale ajouté via ajax #}
            <div id="pollModuleDisplayAllResult_{{ module.token }}_container"></div>
        </div>
    {% endif %}
{% endblock moduleBody %}

{#{% block moduleFooter %}{% endblock moduleFooter %}#}

{% block module_modal_container %}{% endblock module_modal_container %}

src/AppBundle/Resources/views/Event/module/kittyModule.html.twig
{% extends "@App/Event/module/displayModule.html.twig" %}

{% block moduleCardClass %}c-dark{% endblock moduleCardClass %}
{% block moduleHeaderClass %}palette-Green bg{% endblock moduleHeaderClass %}
{% block moduleHeaderAttributs %}{% endblock moduleHeaderAttributs %}
{% block moduleHeader %}
    {{ parent() }}
{% endblock moduleHeader %}

{% block moduleInformationClass %}m-t-20{% endblock %}
{% block moduleInformationAttributs %}{% endblock %}

{% block moduleBodyClass %}m-t-20{% endblock %}
{% block moduleBodyAttributs %}{% endblock %}


{% block moduleBody %}
    <div class="card-body card-padding-sm"></div>
{% endblock moduleBody %}

{% block moduleFooter %}{% endblock moduleFooter %}